### ISSUE TITLE
thank you for your good work.

### ISSUE THREAD

**Issue by alonewolfx2** [fdivitto/ESPWebFramework#1]
firstly thank you for your work. c++ and freertos  very usefull. 
can you add some information about filesystem,create,execute maybe http server?

**Comment by fdivitto** [comment]
HTTP server is under development. I hope to release a first basic version this week. I'm thinking to a web framework like bootle (but working with C++ instead of Python, of course).

About "file system", actually it isn't a file system. I'll use FlashFileSystem to write and read data into the Flash memory, assigning at each block of data a simple name (filename of four characters). For example:
struct MyStore
{
  char name[16];
  char surname[16];
};

//  Save data:
MyStore t;
strcpy(t.name, "Fabrizio");
strcpy(t.surname, "Di Vittorio");
fdv::FlashFileSystem::save("USR0", &t, sizeof(MyStore));

//  Load data:
MyStore t;
fdv::FlashFileSysten::load("USR0", &t);
printf("%s %s", t.name, t.surname);

In this case "USR0" is the file name and the file content is the MyStore structure.

I'd like to configure the ESP8266 using a web interface (as how you do when you configure an access point). Next there will be two options:
1) add user code to handle HTTP requests in the "bootle" way. Just recompile ESPWebFramework application with your code.
2) use a "binary" protocol (vs the AT protocol use in the standard firmware) to comunicate with UART, for example with an Arduino module.

**Comment by alonewolfx2** [comment]
how can i make webcontent.bin ?

**Comment by fdivitto** [comment]
Hello,
it is done automatically when you execute:

make flash

or

make flashweb

The second one flashes only the webcontent directory.

Fabrizio

**Comment by alonewolfx2** [comment]
i tried that one but i have this error message.

```
C:\Espressif\ESPWebFramework-master\projects\ESPWebFramework>make flashweb
python binarydir.py ./webcontent/ webcontent.bin 176128
Traceback (most recent call last):
  File "binarydir.py", line 109, in <module>
    fw.write(struct.pack(str(len(mimetype)) + "sB", mimetype, 0x00))
struct.error: argument for 's' must be a string
make: *** [flashweb] Error 1
```

**Comment by alonewolfx2** [comment]
i tried that one but i have this error message.
```
C:\Espressif\ESPWebFramework-master\projects\ESPWebFramework>make flashweb
python binarydir.py ./webcontent/ webcontent.bin 176128
Traceback (most recent call last):
  File "binarydir.py", line 109, in <module>
    fw.write(struct.pack(str(len(mimetype)) + "sB", mimetype, 0x00))
struct.error: argument for 's' must be a string
make: *** [flashweb] Error 1
```

**Comment by fdivitto** [comment]
Which python version are you using?

**Comment by alonewolfx2** [comment]
2.7.7

**Comment by fdivitto** [comment]
I don't know if this is a python version problem, anyway I'm using 2.7.9 and it works:

C:\Expressif\ESPWebFramework-master\projects\ESPWebFramework>make flashweb
python binarydir.py ./webcontent/ webcontent.bin 176128
out = 7698 bytes   max = 176128 bytes
python C:/Expressif/ESPWebFramework-master/projects/ESPWebFramework/../../SDK/esptool.py --port COM7 write_flash 0x15000 webcontent.bin
Connecting...
Size  7698 Bytes
Erasing flash...
Writing at 0x00016c00... (100 %)

Leaving...

**Comment by fdivitto** [comment]
Have you the same files found in the repository inside "webcontent" (base.html, bkg.gif and styles.css)?

**Comment by alonewolfx2** [comment]
problem solved. it seems binarydir.py working fine on phyton 2.7.9 not 2.7.7

**Comment by fdivitto** [comment]
In my experience also esptool.py cannot work with 2.7.7 (error importing "serial" module).

**Comment by fdivitto** [comment]
Thanks! I've just updated some related files.

**Comment by alonewolfx2** [comment]
i saw but i dont know where is easy_install slimmer file.

**Comment by fdivitto** [comment]
Just execute in the command line:

easy_install slimmer
